### ISSUE TITLE
Scope out the development of a SAFE dAapp for eBTC

### ISSUE THREAD

**Issue by ICEBADGER** [ebtc-protocol/ebtc#542]
**Desired Outcome:**

Develop a SAFE dApp so that users can user their SAFE Wallets with eBTC seamlessly.

The ideal scenario would be to have the dApp listed officially in the [SAFE Apps Ecosystem](https://app.safe.global/apps) to add visibility and credibility.

@mrbasado  please scope this out and add your comments regarding timelines etc.

**Comment by mrbasado** [comment]
With other projects we have. leverage, eth, test suite, looking at mid late Q1 2024

**Comment by ICEBADGER** [comment]
@mrbasado 

Let's make sure we consider the length of time required to jump through the necessary hoops to have the app listed in the official Safe app Ecoystem.

> With other projects we have. leverage, eth, test suite, looking at mid late Q1 2024. will probably take 2ish weeks. seemingly low technical work but verification + giving time for things to go wrong
