### ISSUE TITLE
Last Good Price Optimization

### ISSUE THREAD

**Issue by dapp-whisperer** [ebtc-protocol/ebtc#757]
Storing the lastGoodPrice in the priceFeed contract can be seen as redundant or undesirable in the setup with it as a primaryOracle of the ebtcFeed.

The `priceFeed.lastGoodPrice()` can also become out of date versus the `EbtcFeed.lastGoodPrice()`.

So it could return success, with an outdated value vs the secondaryOracle on ebtcFeed.

- Change the PriceFeed to return failure (0) if it would return last good price.
- For valid prices: It should also just pass through price when storing a price rather than storing it as lastGoodPrice.

**Comment by rayeaster** [comment]
`lastGoodPrice` is a key state variable used in original `PriceFeed` design, especially when both its primary and secondary feed (like Tellor) are not working as expected. 

Removing it will break existing logic

![image](https://github.com/ebtc-protocol/ebtc/assets/1487283/cb2b6264-0eb2-4235-abe9-cec9c7718b31)


https://docs.google.com/spreadsheets/d/18fdtTUoqgmsK3Mb6LBO-6na0oK-Y9LWBqnPCJRp5Hsg/edit#gid=316701608

`EbtcFeed` could check both `lastGoodPrice` and `status` from `PriceFeed` to decide what to do with it. 
For example, if the status is `bothOraclesUntrusted` then `EbtcFeed` could choose to failover to its own secondaryOracle regardless of the `lastGoodPrice` returned by `PriceFee`.

I think this might be the minimal disruptive way to moving forward

**Comment by dapp-whisperer** [comment]
Agree here - we're invalidating the priceFeed as a standalone component.

if we consider the priceFeeds as one unit, it looks similar to above however. We "return the last good price of the parent EbtcFeed"

my inclination is to _adapt all tests_ to the new setup and consider the priceFeeds as one unit

* Foundry suite
* Javascript suite
* PriceFeedTester & UnbiasedTester
